### ISSUE TITLE
Support for RTMPS

### ISSUE THREAD

**Issue by larsweiler** [availo/wowza-vhost-loadbalancer#2]
In https://github.com/availo/wowza-vhost-loadbalancer/blob/master/src/com/availo/wms/plugin/vhostloadbalancer/ModuleLoadBalancerRedirector.java#L336-338 you set HTTPS as a fixed protocol for redirectPort 443. RTMPS also uses Port 443 for delivery, but it is not HTTPS. In my opinion, there should be a new Property where you can specify the Protocol as well – or keep the original protocol.

Unfortunately I'm not able to provide a tested patch, as I have trouble with configuring Eclipse, so that I can compile the Library on my own.

**Comment by brynjare** [comment]
Keeping the original protocol used is most likely the best course of action. Overriding the protocol by using a config option will probably not work with most players unless they are customized to support both RTMP and HTTP.

I will see what I can do next time I have time to take a look at this project. Thanks for the suggestion.

As for Eclipse, I believe I used their Update Site during my last install: http://wowza.com/wowzaide2
Previously I used this .zip file: http://www.wowzamedia.com/downloads/WowzaIDE_beta_2/wowzaproserverproide.zip
(From this thread: http://www.wowza.com/forums/showthread.php?260-plug-in-vs-standalone)

**Comment by brynjare** [comment]
Sorry about the extremely late update here, but I just looked into this while familiarising myself with Wowza Streaming Engine 4.

The lines you highlighted are from onHTTPSessionCreate(), which should never be involved for RTMPS - so even though I agree the protocol assumption is not an ideal solution (as acknowledged by a FIXME comment), I don't believe this should affect RTMPS at all.

Did this cause problems for your setup, or did you just come across it while browsing the code?

FWIW, I configured my loadbalancer and my edge server with RTMPS and HTTPS (both on port 443), and successfully managed to stream RTMPS on the edge server, after connecting to the loadbalancer. Admittedly, I have not done a lot of testing at all - I just confirmed that RTMPS used ModuleLoadBalancerRedirector.onRTMPRequest() as intended.

Please let me know if you actually experienced that RTMPS was affected by the https:// code, or if you had any other problems with that code. I'll leave this issue open for the time being.
